#!/bin/bash -xve
sudo mkdir -p '/usr/local/bin'
sudo chown 'root:admin' '/usr/local/bin'
sudo mkdir -p '/usr/local/etc/bash_completion.d'
sudo chown 'cltbld:admin' '/usr/local/etc/bash_completion.d'
sudo mkdir -p '/usr/local/include'
sudo chown 'root:admin' '/usr/local/include'
sudo mkdir -p '/usr/local/lib'
sudo chown 'root:admin' '/usr/local/lib'
sudo mkdir -p '/usr/local/lib/perl5/site_perl'
sudo chown 'cltbld:admin' '/usr/local/lib/perl5/site_perl'
sudo mkdir -p '/usr/local/lib/perl5/site_perl/5.12.3/darwin-thread-multi-2level/auto/Git'
sudo chown 'cltbld:admin' '/usr/local/lib/perl5/site_perl/5.12.3/darwin-thread-multi-2level/auto/Git'
sudo mkdir -p '/usr/local/lib/perl5/site_perl/Git'
sudo chown 'cltbld:admin' '/usr/local/lib/perl5/site_perl/Git'
sudo mkdir -p '/usr/local/lib/perl5/site_perl/Git/SVN'
sudo chown 'cltbld:admin' '/usr/local/lib/perl5/site_perl/Git/SVN'
sudo mkdir -p '/usr/local/lib/perl5/site_perl/Git/SVN/Memoize'
sudo chown 'cltbld:admin' '/usr/local/lib/perl5/site_perl/Git/SVN/Memoize'
sudo mkdir -p '/usr/local/share'
sudo chown 'root:admin' '/usr/local/share'
sudo mkdir -p '/usr/local/share/aclocal'
sudo chown 'cltbld:admin' '/usr/local/share/aclocal'
sudo mkdir -p '/usr/local/share/doc'
sudo chown 'root:admin' '/usr/local/share/doc'
sudo mkdir -p '/usr/local/share/locale/be/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/be/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/ca/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/ca/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/cs/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/cs/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/da/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/da/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/de/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/de/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/el/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/el/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/en@boldquot/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/en@boldquot/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/en@quot/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/en@quot/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/eo/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/eo/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/es/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/es/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/et/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/et/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/fi/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/fi/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/fr/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/fr/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/gl/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/gl/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/hu/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/hu/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/id/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/id/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/it/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/it/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/ja/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/ja/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/nb/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/nb/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/nl/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/nl/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/pl/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/pl/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/pt/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/pt/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/pt_BR/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/pt_BR/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/ro/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/ro/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/ru/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/ru/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/sk/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/sk/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/sv/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/sv/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/tr/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/tr/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/uk/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/uk/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/zh_CN/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/zh_CN/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/locale/zh_TW/LC_MESSAGES'
sudo chown 'cltbld:admin' '/usr/local/share/locale/zh_TW/LC_MESSAGES'
sudo mkdir -p '/usr/local/share/man/man1'
sudo chown 'root:admin' '/usr/local/share/man/man1'
sudo mkdir -p '/usr/local/share/man/man3'
sudo chown 'root:admin' '/usr/local/share/man/man3'
sudo mkdir -p '/usr/local/share/man/man5'
sudo chown 'root:admin' '/usr/local/share/man/man5'
sudo mkdir -p '/usr/local/share/man/man7'
sudo chown 'root:admin' '/usr/local/share/man/man7'
sudo mkdir -p '/usr/local/share/zsh/site-functions'
sudo chown 'cltbld:admin' '/usr/local/share/zsh/site-functions'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/c++-4.6' '/usr/local/bin/c++-4.6'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/bin/ccmake' '/usr/local/bin/ccmake'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/bin/cmake' '/usr/local/bin/cmake'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/bin/cmakexbuild' '/usr/local/bin/cmakexbuild'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/bin/cpack' '/usr/local/bin/cpack'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/cpp-4.6' '/usr/local/bin/cpp-4.6'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/bin/ctest' '/usr/local/bin/ctest'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/g++-4.6' '/usr/local/bin/g++-4.6'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/gcc-4.6' '/usr/local/bin/gcc-4.6'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/gcov-4.6' '/usr/local/bin/gcov-4.6'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git' '/usr/local/bin/git'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-credential-osxkeychain' '/usr/local/bin/git-credential-osxkeychain'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-cvsserver' '/usr/local/bin/git-cvsserver'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-receive-pack' '/usr/local/bin/git-receive-pack'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-remote-bzr' '/usr/local/bin/git-remote-bzr'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-remote-hg' '/usr/local/bin/git-remote-hg'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-shell' '/usr/local/bin/git-shell'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-subtree' '/usr/local/bin/git-subtree'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-upload-archive' '/usr/local/bin/git-upload-archive'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/git-upload-pack' '/usr/local/bin/git-upload-pack'
sudo ln -f -s '../Cellar/git/1.8.5.1/bin/gitk' '/usr/local/bin/gitk'
sudo ln -f -s '../Cellar/gnupg/1.4.15/bin/gpg' '/usr/local/bin/gpg'
sudo ln -f -s '../Cellar/gnupg/1.4.15/bin/gpg-zip' '/usr/local/bin/gpg-zip'
sudo ln -f -s '../Cellar/gnupg/1.4.15/bin/gpgsplit' '/usr/local/bin/gpgsplit'
sudo ln -f -s '../Cellar/gnupg/1.4.15/bin/gpgv' '/usr/local/bin/gpgv'
sudo ln -f -s '../Cellar/gnu-tar/1.27/bin/gtar' '/usr/local/bin/gtar'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/x86_64-apple-darwin11.2.0-c++-4.6' '/usr/local/bin/x86_64-apple-darwin11.2.0-c++-4.6'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/x86_64-apple-darwin11.2.0-g++-4.6' '/usr/local/bin/x86_64-apple-darwin11.2.0-g++-4.6'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/x86_64-apple-darwin11.2.0-gcc-4.6' '/usr/local/bin/x86_64-apple-darwin11.2.0-gcc-4.6'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/bin/x86_64-apple-darwin11.2.0-gcc-4.6.3' '/usr/local/bin/x86_64-apple-darwin11.2.0-gcc-4.6.3'
sudo ln -f -s '../../Cellar/git/1.8.5.1/etc/bash_completion.d/git-completion.bash' '/usr/local/etc/bash_completion.d/git-completion.bash'
sudo ln -f -s '../../Cellar/git/1.8.5.1/etc/bash_completion.d/git-prompt.sh' '/usr/local/etc/bash_completion.d/git-prompt.sh'
sudo ln -f -s '../Cellar/gmp/5.1.3/include/gmp.h' '/usr/local/include/gmp.h'
sudo ln -f -s '../Cellar/gmp/5.1.3/include/gmpxx.h' '/usr/local/include/gmpxx.h'
sudo ln -f -s '../Cellar/libmpc/1.0.1/include/mpc.h' '/usr/local/include/mpc.h'
sudo ln -f -s '../Cellar/mpfr/3.1.2/include/mpf2mpfr.h' '/usr/local/include/mpf2mpfr.h'
sudo ln -f -s '../Cellar/mpfr/3.1.2/include/mpfr.h' '/usr/local/include/mpfr.h'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmp.10.dylib' '/usr/local/lib/libgmp.10.dylib'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmp.a' '/usr/local/lib/libgmp.a'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmp.dylib' '/usr/local/lib/libgmp.dylib'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmpxx.4.dylib' '/usr/local/lib/libgmpxx.4.dylib'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmpxx.a' '/usr/local/lib/libgmpxx.a'
sudo ln -f -s '../Cellar/gmp/5.1.3/lib/libgmpxx.dylib' '/usr/local/lib/libgmpxx.dylib'
sudo ln -f -s '../Cellar/libmpc/1.0.1/lib/libmpc.3.dylib' '/usr/local/lib/libmpc.3.dylib'
sudo ln -f -s '../Cellar/libmpc/1.0.1/lib/libmpc.a' '/usr/local/lib/libmpc.a'
sudo ln -f -s '../Cellar/libmpc/1.0.1/lib/libmpc.dylib' '/usr/local/lib/libmpc.dylib'
sudo ln -f -s '../Cellar/mpfr/3.1.2/lib/libmpfr.4.dylib' '/usr/local/lib/libmpfr.4.dylib'
sudo ln -f -s '../Cellar/mpfr/3.1.2/lib/libmpfr.a' '/usr/local/lib/libmpfr.a'
sudo ln -f -s '../Cellar/mpfr/3.1.2/lib/libmpfr.dylib' '/usr/local/lib/libmpfr.dylib'
sudo ln -f -s '../../../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/5.12.3/darwin-thread-multi-2level/auto/Git/.packlist' '/usr/local/lib/perl5/site_perl/5.12.3/darwin-thread-multi-2level/auto/Git/.packlist'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git.pm' '/usr/local/lib/perl5/site_perl/Git.pm'
sudo ln -f -s '../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/I18N.pm' '/usr/local/lib/perl5/site_perl/Git/I18N.pm'
sudo ln -f -s '../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/IndexInfo.pm' '/usr/local/lib/perl5/site_perl/Git/IndexInfo.pm'
sudo ln -f -s '../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN.pm' '/usr/local/lib/perl5/site_perl/Git/SVN.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Editor.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Editor.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Fetcher.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Fetcher.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/GlobSpec.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/GlobSpec.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Log.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Log.pm'
sudo ln -f -s '../../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Memoize/YAML.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Memoize/YAML.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Migration.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Migration.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Prompt.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Prompt.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Ra.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Ra.pm'
sudo ln -f -s '../../../../../Cellar/git/1.8.5.1/lib/perl5/site_perl/Git/SVN/Utils.pm' '/usr/local/lib/perl5/site_perl/Git/SVN/Utils.pm'
sudo ln -f -s '../../Cellar/cmake/2.8.12.1/share/aclocal/cmake.m4' '/usr/local/share/aclocal/cmake.m4'
sudo ln -f -s '../Cellar/cmake/2.8.12.1/share/cmake' '/usr/local/share/cmake'
sudo ln -f -s '../../Cellar/cmake/2.8.12.1/share/doc/cmake' '/usr/local/share/doc/cmake'
sudo ln -f -s '../../Cellar/git/1.8.5.1/share/doc/git-doc' '/usr/local/share/doc/git-doc'
sudo ln -f -s '../../Cellar/mpfr/3.1.2/share/doc/mpfr' '/usr/local/share/doc/mpfr'
sudo ln -f -s '../Cellar/gcc-4.6/4.6.3/share/gcc-4.6.3' '/usr/local/share/gcc-4.6.3'
sudo ln -f -s '../Cellar/git/1.8.5.1/share/git-core' '/usr/local/share/git-core'
sudo ln -f -s '../Cellar/git/1.8.5.1/share/git-gui' '/usr/local/share/git-gui'
sudo ln -f -s '../Cellar/git/1.8.5.1/share/gitk' '/usr/local/share/gitk'
sudo ln -f -s '../Cellar/git/1.8.5.1/share/gitweb' '/usr/local/share/gitweb'
sudo ln -f -s '../Cellar/gnupg/1.4.15/share/gnupg' '/usr/local/share/gnupg'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/be/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/be/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/ca/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/ca/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/cs/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/cs/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/da/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/da/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/de/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/de/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/el/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/el/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/en@boldquot/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/en@boldquot/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/en@quot/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/en@quot/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/eo/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/eo/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/es/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/es/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/et/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/et/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/fi/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/fi/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/fr/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/fr/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/gl/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/gl/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/hu/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/hu/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/id/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/id/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/it/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/it/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/ja/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/ja/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/nb/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/nb/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/nl/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/nl/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/pl/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/pl/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/pt/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/pt/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/pt_BR/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/pt_BR/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/ro/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/ro/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/ru/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/ru/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/sk/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/sk/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/sv/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/sv/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/tr/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/tr/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/uk/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/uk/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/zh_CN/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/zh_CN/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../../Cellar/gnupg/1.4.15/share/locale/zh_TW/LC_MESSAGES/gnupg.mo' '/usr/local/share/locale/zh_TW/LC_MESSAGES/gnupg.mo'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/ccmake.1' '/usr/local/share/man/man1/ccmake.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmake.1' '/usr/local/share/man/man1/cmake.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakecommands.1' '/usr/local/share/man/man1/cmakecommands.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakecompat.1' '/usr/local/share/man/man1/cmakecompat.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakemodules.1' '/usr/local/share/man/man1/cmakemodules.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakepolicies.1' '/usr/local/share/man/man1/cmakepolicies.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakeprops.1' '/usr/local/share/man/man1/cmakeprops.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cmakevars.1' '/usr/local/share/man/man1/cmakevars.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/cpack.1' '/usr/local/share/man/man1/cpack.1'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man1/cpp-4.6.1' '/usr/local/share/man/man1/cpp-4.6.1'
sudo ln -f -s '../../../Cellar/cmake/2.8.12.1/share/man/man1/ctest.1' '/usr/local/share/man/man1/ctest.1'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man1/g++-4.6.1' '/usr/local/share/man/man1/g++-4.6.1'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man1/gcc-4.6.1' '/usr/local/share/man/man1/gcc-4.6.1'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man1/gcov-4.6.1' '/usr/local/share/man/man1/gcov-4.6.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-add.1' '/usr/local/share/man/man1/git-add.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-am.1' '/usr/local/share/man/man1/git-am.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-annotate.1' '/usr/local/share/man/man1/git-annotate.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-apply.1' '/usr/local/share/man/man1/git-apply.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-archimport.1' '/usr/local/share/man/man1/git-archimport.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-archive.1' '/usr/local/share/man/man1/git-archive.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-bisect.1' '/usr/local/share/man/man1/git-bisect.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-blame.1' '/usr/local/share/man/man1/git-blame.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-branch.1' '/usr/local/share/man/man1/git-branch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-bundle.1' '/usr/local/share/man/man1/git-bundle.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cat-file.1' '/usr/local/share/man/man1/git-cat-file.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-check-attr.1' '/usr/local/share/man/man1/git-check-attr.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-check-ignore.1' '/usr/local/share/man/man1/git-check-ignore.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-check-mailmap.1' '/usr/local/share/man/man1/git-check-mailmap.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-check-ref-format.1' '/usr/local/share/man/man1/git-check-ref-format.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-checkout-index.1' '/usr/local/share/man/man1/git-checkout-index.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-checkout.1' '/usr/local/share/man/man1/git-checkout.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cherry-pick.1' '/usr/local/share/man/man1/git-cherry-pick.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cherry.1' '/usr/local/share/man/man1/git-cherry.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-citool.1' '/usr/local/share/man/man1/git-citool.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-clean.1' '/usr/local/share/man/man1/git-clean.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-clone.1' '/usr/local/share/man/man1/git-clone.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-column.1' '/usr/local/share/man/man1/git-column.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-commit-tree.1' '/usr/local/share/man/man1/git-commit-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-commit.1' '/usr/local/share/man/man1/git-commit.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-config.1' '/usr/local/share/man/man1/git-config.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-count-objects.1' '/usr/local/share/man/man1/git-count-objects.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-credential-cache--daemon.1' '/usr/local/share/man/man1/git-credential-cache--daemon.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-credential-cache.1' '/usr/local/share/man/man1/git-credential-cache.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-credential-store.1' '/usr/local/share/man/man1/git-credential-store.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-credential.1' '/usr/local/share/man/man1/git-credential.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cvsexportcommit.1' '/usr/local/share/man/man1/git-cvsexportcommit.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cvsimport.1' '/usr/local/share/man/man1/git-cvsimport.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-cvsserver.1' '/usr/local/share/man/man1/git-cvsserver.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-daemon.1' '/usr/local/share/man/man1/git-daemon.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-describe.1' '/usr/local/share/man/man1/git-describe.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-diff-files.1' '/usr/local/share/man/man1/git-diff-files.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-diff-index.1' '/usr/local/share/man/man1/git-diff-index.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-diff-tree.1' '/usr/local/share/man/man1/git-diff-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-diff.1' '/usr/local/share/man/man1/git-diff.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-difftool.1' '/usr/local/share/man/man1/git-difftool.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fast-export.1' '/usr/local/share/man/man1/git-fast-export.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fast-import.1' '/usr/local/share/man/man1/git-fast-import.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fetch-pack.1' '/usr/local/share/man/man1/git-fetch-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fetch.1' '/usr/local/share/man/man1/git-fetch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-filter-branch.1' '/usr/local/share/man/man1/git-filter-branch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fmt-merge-msg.1' '/usr/local/share/man/man1/git-fmt-merge-msg.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-for-each-ref.1' '/usr/local/share/man/man1/git-for-each-ref.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-format-patch.1' '/usr/local/share/man/man1/git-format-patch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fsck-objects.1' '/usr/local/share/man/man1/git-fsck-objects.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-fsck.1' '/usr/local/share/man/man1/git-fsck.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-gc.1' '/usr/local/share/man/man1/git-gc.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-get-tar-commit-id.1' '/usr/local/share/man/man1/git-get-tar-commit-id.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-grep.1' '/usr/local/share/man/man1/git-grep.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-gui.1' '/usr/local/share/man/man1/git-gui.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-hash-object.1' '/usr/local/share/man/man1/git-hash-object.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-help.1' '/usr/local/share/man/man1/git-help.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-http-backend.1' '/usr/local/share/man/man1/git-http-backend.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-http-fetch.1' '/usr/local/share/man/man1/git-http-fetch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-http-push.1' '/usr/local/share/man/man1/git-http-push.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-imap-send.1' '/usr/local/share/man/man1/git-imap-send.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-index-pack.1' '/usr/local/share/man/man1/git-index-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-init-db.1' '/usr/local/share/man/man1/git-init-db.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-init.1' '/usr/local/share/man/man1/git-init.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-instaweb.1' '/usr/local/share/man/man1/git-instaweb.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-log.1' '/usr/local/share/man/man1/git-log.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-lost-found.1' '/usr/local/share/man/man1/git-lost-found.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-ls-files.1' '/usr/local/share/man/man1/git-ls-files.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-ls-remote.1' '/usr/local/share/man/man1/git-ls-remote.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-ls-tree.1' '/usr/local/share/man/man1/git-ls-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mailinfo.1' '/usr/local/share/man/man1/git-mailinfo.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mailsplit.1' '/usr/local/share/man/man1/git-mailsplit.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge-base.1' '/usr/local/share/man/man1/git-merge-base.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge-file.1' '/usr/local/share/man/man1/git-merge-file.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge-index.1' '/usr/local/share/man/man1/git-merge-index.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge-one-file.1' '/usr/local/share/man/man1/git-merge-one-file.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge-tree.1' '/usr/local/share/man/man1/git-merge-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-merge.1' '/usr/local/share/man/man1/git-merge.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mergetool--lib.1' '/usr/local/share/man/man1/git-mergetool--lib.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mergetool.1' '/usr/local/share/man/man1/git-mergetool.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mktag.1' '/usr/local/share/man/man1/git-mktag.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mktree.1' '/usr/local/share/man/man1/git-mktree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-mv.1' '/usr/local/share/man/man1/git-mv.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-name-rev.1' '/usr/local/share/man/man1/git-name-rev.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-notes.1' '/usr/local/share/man/man1/git-notes.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-p4.1' '/usr/local/share/man/man1/git-p4.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-pack-objects.1' '/usr/local/share/man/man1/git-pack-objects.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-pack-redundant.1' '/usr/local/share/man/man1/git-pack-redundant.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-pack-refs.1' '/usr/local/share/man/man1/git-pack-refs.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-parse-remote.1' '/usr/local/share/man/man1/git-parse-remote.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-patch-id.1' '/usr/local/share/man/man1/git-patch-id.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-peek-remote.1' '/usr/local/share/man/man1/git-peek-remote.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-prune-packed.1' '/usr/local/share/man/man1/git-prune-packed.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-prune.1' '/usr/local/share/man/man1/git-prune.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-pull.1' '/usr/local/share/man/man1/git-pull.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-push.1' '/usr/local/share/man/man1/git-push.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-quiltimport.1' '/usr/local/share/man/man1/git-quiltimport.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-read-tree.1' '/usr/local/share/man/man1/git-read-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-rebase.1' '/usr/local/share/man/man1/git-rebase.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-receive-pack.1' '/usr/local/share/man/man1/git-receive-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-reflog.1' '/usr/local/share/man/man1/git-reflog.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-relink.1' '/usr/local/share/man/man1/git-relink.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-remote-ext.1' '/usr/local/share/man/man1/git-remote-ext.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-remote-fd.1' '/usr/local/share/man/man1/git-remote-fd.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-remote-testgit.1' '/usr/local/share/man/man1/git-remote-testgit.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-remote.1' '/usr/local/share/man/man1/git-remote.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-repack.1' '/usr/local/share/man/man1/git-repack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-replace.1' '/usr/local/share/man/man1/git-replace.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-repo-config.1' '/usr/local/share/man/man1/git-repo-config.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-request-pull.1' '/usr/local/share/man/man1/git-request-pull.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-rerere.1' '/usr/local/share/man/man1/git-rerere.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-reset.1' '/usr/local/share/man/man1/git-reset.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-rev-list.1' '/usr/local/share/man/man1/git-rev-list.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-rev-parse.1' '/usr/local/share/man/man1/git-rev-parse.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-revert.1' '/usr/local/share/man/man1/git-revert.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-rm.1' '/usr/local/share/man/man1/git-rm.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-send-email.1' '/usr/local/share/man/man1/git-send-email.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-send-pack.1' '/usr/local/share/man/man1/git-send-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-sh-i18n--envsubst.1' '/usr/local/share/man/man1/git-sh-i18n--envsubst.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-sh-i18n.1' '/usr/local/share/man/man1/git-sh-i18n.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-sh-setup.1' '/usr/local/share/man/man1/git-sh-setup.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-shell.1' '/usr/local/share/man/man1/git-shell.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-shortlog.1' '/usr/local/share/man/man1/git-shortlog.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-show-branch.1' '/usr/local/share/man/man1/git-show-branch.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-show-index.1' '/usr/local/share/man/man1/git-show-index.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-show-ref.1' '/usr/local/share/man/man1/git-show-ref.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-show.1' '/usr/local/share/man/man1/git-show.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-stage.1' '/usr/local/share/man/man1/git-stage.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-stash.1' '/usr/local/share/man/man1/git-stash.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-status.1' '/usr/local/share/man/man1/git-status.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-stripspace.1' '/usr/local/share/man/man1/git-stripspace.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-submodule.1' '/usr/local/share/man/man1/git-submodule.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-svn.1' '/usr/local/share/man/man1/git-svn.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-symbolic-ref.1' '/usr/local/share/man/man1/git-symbolic-ref.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-tag.1' '/usr/local/share/man/man1/git-tag.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-tar-tree.1' '/usr/local/share/man/man1/git-tar-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-unpack-file.1' '/usr/local/share/man/man1/git-unpack-file.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-unpack-objects.1' '/usr/local/share/man/man1/git-unpack-objects.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-update-index.1' '/usr/local/share/man/man1/git-update-index.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-update-ref.1' '/usr/local/share/man/man1/git-update-ref.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-update-server-info.1' '/usr/local/share/man/man1/git-update-server-info.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-upload-archive.1' '/usr/local/share/man/man1/git-upload-archive.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-upload-pack.1' '/usr/local/share/man/man1/git-upload-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-var.1' '/usr/local/share/man/man1/git-var.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-verify-pack.1' '/usr/local/share/man/man1/git-verify-pack.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-verify-tag.1' '/usr/local/share/man/man1/git-verify-tag.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-web--browse.1' '/usr/local/share/man/man1/git-web--browse.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-whatchanged.1' '/usr/local/share/man/man1/git-whatchanged.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git-write-tree.1' '/usr/local/share/man/man1/git-write-tree.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/git.1' '/usr/local/share/man/man1/git.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/gitk.1' '/usr/local/share/man/man1/gitk.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/gitremote-helpers.1' '/usr/local/share/man/man1/gitremote-helpers.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man1/gitweb.1' '/usr/local/share/man/man1/gitweb.1'
sudo ln -f -s '../../../Cellar/gnupg/1.4.15/share/man/man1/gpg-zip.1' '/usr/local/share/man/man1/gpg-zip.1'
sudo ln -f -s '../../../Cellar/gnupg/1.4.15/share/man/man1/gpg.1' '/usr/local/share/man/man1/gpg.1'
sudo ln -f -s '../../../Cellar/gnupg/1.4.15/share/man/man1/gpg.ru.1' '/usr/local/share/man/man1/gpg.ru.1'
sudo ln -f -s '../../../Cellar/gnupg/1.4.15/share/man/man1/gpgv.1' '/usr/local/share/man/man1/gpgv.1'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git.3pm' '/usr/local/share/man/man3/Git.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::I18N.3pm' '/usr/local/share/man/man3/Git::I18N.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Editor.3pm' '/usr/local/share/man/man3/Git::SVN::Editor.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Fetcher.3pm' '/usr/local/share/man/man3/Git::SVN::Fetcher.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Memoize::YAML.3pm' '/usr/local/share/man/man3/Git::SVN::Memoize::YAML.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Prompt.3pm' '/usr/local/share/man/man3/Git::SVN::Prompt.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Ra.3pm' '/usr/local/share/man/man3/Git::SVN::Ra.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man3/Git::SVN::Utils.3pm' '/usr/local/share/man/man3/Git::SVN::Utils.3pm'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/gitattributes.5' '/usr/local/share/man/man5/gitattributes.5'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/githooks.5' '/usr/local/share/man/man5/githooks.5'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/gitignore.5' '/usr/local/share/man/man5/gitignore.5'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/gitmodules.5' '/usr/local/share/man/man5/gitmodules.5'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/gitrepository-layout.5' '/usr/local/share/man/man5/gitrepository-layout.5'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man5/gitweb.conf.5' '/usr/local/share/man/man5/gitweb.conf.5'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man7/fsf-funding.7' '/usr/local/share/man/man7/fsf-funding.7'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man7/gfdl.7' '/usr/local/share/man/man7/gfdl.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitcli.7' '/usr/local/share/man/man7/gitcli.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitcore-tutorial.7' '/usr/local/share/man/man7/gitcore-tutorial.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitcredentials.7' '/usr/local/share/man/man7/gitcredentials.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitcvs-migration.7' '/usr/local/share/man/man7/gitcvs-migration.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitdiffcore.7' '/usr/local/share/man/man7/gitdiffcore.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitglossary.7' '/usr/local/share/man/man7/gitglossary.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitnamespaces.7' '/usr/local/share/man/man7/gitnamespaces.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitrevisions.7' '/usr/local/share/man/man7/gitrevisions.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gittutorial-2.7' '/usr/local/share/man/man7/gittutorial-2.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gittutorial.7' '/usr/local/share/man/man7/gittutorial.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/man/man7/gitworkflows.7' '/usr/local/share/man/man7/gitworkflows.7'
sudo ln -f -s '../../../Cellar/gnupg/1.4.15/share/man/man7/gnupg.7' '/usr/local/share/man/man7/gnupg.7'
sudo ln -f -s '../../../Cellar/gcc-4.6/4.6.3/share/man/man7/gpl.7' '/usr/local/share/man/man7/gpl.7'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/zsh/site-functions/_git' '/usr/local/share/zsh/site-functions/_git'
sudo ln -f -s '../../../Cellar/git/1.8.5.1/share/zsh/site-functions/git-completion.bash' '/usr/local/share/zsh/site-functions/git-completion.bash'
